### ISSUE TITLE
flynn logs without params throws "index out of range"

### ISSUE THREAD

**Issue by mbonaci** [flynn-archive/flynn-demo#13]
That should spit out some usage info or something, right?

``` sh
vagrant@packer-virtualbox:/vagrant$ cd nodejs-example/
vagrant@packer-virtualbox:/vagrant/nodejs-example$ flynn ps
web.Ds-qX-jxFzL6EmEEIz0YTw
web.mos9oab-OiN6VpJamtTvdA
web.z7zg9OZJy3WD6cLybuevBQ
vagrant@packer-virtualbox:/vagrant/nodejs-example$ flynn logs
panic: runtime error: index out of range

goroutine 1 [running]:
runtime.panic(0x671c00, 0x9970f7)
        /usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
main.runLogs(0x995520, 0xc21000a020, 0x0, 0x0)
        /vagrant/src/github.com/flynn/flynn-cli/logs.go:15 +0xf3
main.main()
        /vagrant/src/github.com/flynn/flynn-cli/main.go:107 +0x3fc
vagrant@packer-virtualbox:/vagrant/nodejs-example$
vagrant@packer-virtualbox:/vagrant/nodejs-example$ flynn logs web.1
Unexpected error: 404 Not Found
```

**Comment by titanous** [comment]
Yeah, it shouldn't panic. Use one of the job ids from `flynn ps` instead of `web.1`.

**Comment by mbonaci** [comment]
Yep, that does the trick:

``` sh
vagrant@packer-virtualbox:/vagrant/nodejs-example$ flynn logs web.Ds-qX-jxFzL6EmEEIz0YTw
☺      ‼Listening on 55001
```

**Comment by titanous** [comment]
Cool, looks like there's some log framing that I need to strip too...
